/*
 * landlord self-check: run by `make test`, exits non-zero on failure.
 *
 * Two seams are tested: the rules (cards -> hand type) and a whole game
 * (seed -> one finished game).
 */

#undef NDEBUG
#include <assert.h>

#include "landlord.h"

/* ************************************************************
 * rules: cards -> hand type
 * ************************************************************/

typedef struct {
  const char *cards;
  int type;
} parse_case_t;

static const parse_case_t parse_cases[] = {
    {"♣3", Hand_Format(HAND_PRIMAL_SOLO, HAND_KICKER_NONE, HAND_CHAINLESS)},
    {"♣3 ♠3", Hand_Format(HAND_PRIMAL_PAIR, HAND_KICKER_NONE, HAND_CHAINLESS)},
    {"♠r ♠R", Hand_Format(HAND_PRIMAL_NUKE, HAND_KICKER_NONE, HAND_CHAINLESS)},
    {"♠6 ♥6 ♦6",
     Hand_Format(HAND_PRIMAL_TRIO, HAND_KICKER_NONE, HAND_CHAINLESS)},
    {"♣3 ♠3 ♥3 ♥7",
     Hand_Format(HAND_PRIMAL_TRIO, HAND_KICKER_SOLO, HAND_CHAINLESS)},
    {"♣3 ♣5 ♠5 ♠3 ♥5",
     Hand_Format(HAND_PRIMAL_TRIO, HAND_KICKER_PAIR, HAND_CHAINLESS)},
    {"♣7 ♠7 ♥7 ♦7",
     Hand_Format(HAND_PRIMAL_BOMB, HAND_KICKER_NONE, HAND_CHAINLESS)},
    {"♣3 ♣4 ♠5 ♠6 ♥7",
     Hand_Format(HAND_PRIMAL_SOLO, HAND_KICKER_NONE, HAND_CHAIN)},
    {"♣3 ♠4 ♦6 ♥8 ♠7 ♦5 ♦9 ♦T ♦J",
     Hand_Format(HAND_PRIMAL_SOLO, HAND_KICKER_NONE, HAND_CHAIN)},
    {"♣4 ♠4 ♠5 ♥6 ♥5 ♦6",
     Hand_Format(HAND_PRIMAL_PAIR, HAND_KICKER_NONE, HAND_CHAIN)},
    {"♣4 ♠4 ♦4 ♥5 ♠5 ♦5",
     Hand_Format(HAND_PRIMAL_TRIO, HAND_KICKER_NONE, HAND_CHAIN)},
    {"♣3 ♠3 ♦3 ♥4 ♠4 ♦4 ♦6 ♦9",
     Hand_Format(HAND_PRIMAL_TRIO, HAND_KICKER_SOLO, HAND_CHAIN)},
    {"♣3 ♠3 ♦3 ♥4 ♠4 ♦4 ♦6 ♠6 ♦9 ♠9",
     Hand_Format(HAND_PRIMAL_TRIO, HAND_KICKER_PAIR, HAND_CHAIN)},
    {"♣4 ♠4 ♦4 ♥4 ♠5 ♦6",
     Hand_Format(HAND_PRIMAL_FOUR, HAND_KICKER_DUAL_SOLO, HAND_CHAINLESS)},
    {"♣3 ♠3 ♦3 ♥3 ♠6 ♦6 ♦9 ♠9",
     Hand_Format(HAND_PRIMAL_FOUR, HAND_KICKER_DUAL_PAIR, HAND_CHAINLESS)},
    /* not a hand */
    {"♣3 ♠4", HAND_NONE},
    {"♣3 ♠4 ♦5 ♥6", HAND_NONE},
    {"♣3 ♠3 ♦4 ♥4", HAND_NONE},
    {"♣3 ♠4 ♦5 ♥6 ♠7 ♦8 ♦9 ♦T ♦J ♦Q ♦K ♦A ♦2 ♦r ♦R", HAND_NONE},
};

static void test_rules(void) {
  size_t i;

  printf("testing rules...\n");
  for (i = 0; i < sizeof(parse_cases) / sizeof(parse_cases[0]); i++) {
    card_array_t cards;
    hand_t hand;
    int type;

    CardArray_InitFromString(&cards, parse_cases[i].cards);
    type = Hand_Parse(&hand, &cards);
    if (type != parse_cases[i].type) {
      printf(
          "  [%s] parsed as 0x%02x, expected 0x%02x\n", parse_cases[i].cards,
          (unsigned)type, (unsigned)parse_cases[i].type);
      assert(0);
    }
  }
}

/* ************************************************************
 * card array: operations on a full 54 card array stay inside it
 * ************************************************************/

static void test_card_array(void) {
  /* on the heap so that a sanitizer sees any access past the end */
  card_array_t *full = malloc(sizeof(card_array_t));
  card_array_t reference;
  int i;

  printf("testing card array...\n");
  CardArray_Reset(&reference);

  CardArray_Reset(full);
  for (i = 0; i < CARD_SET_LENGTH; i++) {
    assert(CardArray_PopFront(full) == reference.cards[i]);
    assert(full->length == CARD_SET_LENGTH - 1 - i);
  }
  assert(CardArray_PopFront(full) == 0);

  CardArray_Reset(full);
  assert(CardArray_DropFront(full, 4) == 4);
  assert(full->length == CARD_SET_LENGTH - 4);
  assert(full->cards[0] == reference.cards[4]);
  assert(full->cards[full->length - 1] == reference.cards[CARD_SET_LENGTH - 1]);
  assert(CardArray_DropFront(full, CARD_SET_LENGTH) == CARD_SET_LENGTH - 4);
  assert(full->length == 0);

  CardArray_Reset(full);
  CardArray_PushBack(full, reference.cards[0]); /* full, must be ignored */
  assert(full->length == CARD_SET_LENGTH);
  assert(CardArray_PushFront(full, reference.cards[0]) == 0);
  assert(CardArray_PopBack(full) == reference.cards[CARD_SET_LENGTH - 1]);

  free(full);
}

/* ************************************************************
 * whole game: seed -> one finished game
 * ************************************************************/

#define TEST_SEED_BEGIN 10000
#define TEST_SEED_END 11000

/* ************************************************************
 * baseline: what every seed played like when it was last recorded
 * ************************************************************/

typedef struct {
  int winner;
  int landlord;
  int bid;
  uint32_t plays; /* FNV-1a of every card played, in order */
} game_summary_t;

/* generated by `make landlord-baseline`, do not edit */
static const game_summary_t baseline[] = {
#include "baseline.c.inc"
};

static game_summary_t summarize(const game_t *game) {
  game_summary_t summary;
  int i;

  summary.winner = game->winner;
  summary.landlord = game->landlord;
  summary.bid = game->bid;
  summary.plays = 2166136261u;
  for (i = 0; i < game->cardRecord.length; i++)
    summary.plays = (summary.plays ^ game->cardRecord.cards[i]) * 16777619u;

  return summary;
}

static void print_baseline(void) {
  game_t game;
  uint32_t seed;

  Game_Init(&game);
  for (seed = TEST_SEED_BEGIN; seed < TEST_SEED_END; seed++) {
    game_summary_t s;

    Game_Play(&game, seed);
    s = summarize(&game);
    printf(
        "{%d, %d, %d, 0x%08xu}, /* %u */\n", s.winner, s.landlord, s.bid,
        (unsigned)s.plays, (unsigned)seed);
    Game_Reset(&game);
  }
  Game_Clear(&game);
}

static void test_baseline(void) {
  game_t game;
  uint32_t seed;

  printf("testing baseline...\n");
  assert(
      sizeof(baseline) / sizeof(baseline[0]) ==
      TEST_SEED_END - TEST_SEED_BEGIN);

  Game_Init(&game);
  for (seed = TEST_SEED_BEGIN; seed < TEST_SEED_END; seed++) {
    const game_summary_t *want = &baseline[seed - TEST_SEED_BEGIN];
    game_summary_t got;

    Game_Play(&game, seed);
    got = summarize(&game);
    if (got.landlord != want->landlord || got.bid != want->bid) {
      printf(
          "  seed %u: bidding differs, landlord %d bid %d, baseline %d bid "
          "%d\n",
          (unsigned)seed, got.landlord, got.bid, want->landlord, want->bid);
      assert(0);
    }
    if (got.plays != want->plays) {
      printf(
          "  seed %u: cards played differ, 0x%08x, baseline 0x%08x\n",
          (unsigned)seed, (unsigned)got.plays, (unsigned)want->plays);
      assert(0);
    }
    if (got.winner != want->winner) {
      printf(
          "  seed %u: winner %d, baseline %d\n", (unsigned)seed, got.winner,
          want->winner);
      assert(0);
    }
    Game_Reset(&game);
  }
  Game_Clear(&game);
}

/* same cards in the same order */
static int same_sequence(const card_array_t *a, const card_array_t *b) {
  return a->length == b->length &&
         memcmp(a->cards, b->cards, (size_t)a->length) == 0;
}

/* the same seed must give the same game, whatever was played before it */
static void test_determinism(void) {
  game_t game;
  game_t first;
  uint32_t seed;

  printf("testing determinism...\n");
  Game_Init(&game);
  for (seed = TEST_SEED_BEGIN; seed < TEST_SEED_BEGIN + 20; seed++) {
    Game_Play(&game, seed);
    first = game;
    Game_Reset(&game);

    /* an unrelated game in between must not matter */
    Game_Play(&game, seed + 12345);
    Game_Reset(&game);

    Game_Play(&game, seed);
    if (game.winner != first.winner || game.landlord != first.landlord ||
        game.bid != first.bid ||
        !same_sequence(&game.cardRecord, &first.cardRecord)) {
      printf("  seed %u played differently the second time\n", (unsigned)seed);
      assert(0);
    }
    Game_Reset(&game);
  }
  Game_Clear(&game);
}

static void test_games(void) {
  game_t game;
  uint32_t seed;

  printf("testing games...\n");
  Game_Init(&game);
  for (seed = TEST_SEED_BEGIN; seed < TEST_SEED_END; seed++) {
    Game_Play(&game, seed);
    if (game.status != GameStatus_Over || game.winner < 0 ||
        game.winner >= GAME_PLAYERS ||
        game.players[game.winner].cards.length != 0) {
      printf("  seed %u did not finish with a winner\n", (unsigned)seed);
      assert(0);
    }
    Game_Reset(&game);
  }
  Game_Clear(&game);
}

int main(int argc, char **argv) {
  /* regenerate the baseline instead of testing against it */
  if (argc > 1 && strcmp(argv[1], "--baseline") == 0) {
    print_baseline();
    return 0;
  }

  test_rules();
  test_card_array();
  test_games();
  test_determinism();
  test_baseline();
  printf("landlord: all tests passed\n");
  return 0;
}
