/*
 *  evalarrays.h
 *  evaluator
 *
 *  Created by Master.G on 13-7-25.
 *  Copyright (c) 2013 MED. All rights reserved.
 */

#ifndef EVAL_ARRAYS_H_
#define EVAL_ARRAYS_H_

#define EVAL_USE_HASH

/*
** this is a table lookup for all "flush" hands (e.g.  both
** flushes and straight-flushes.  entries containing a zero
** mean that combination is not possible with a three-card
** flush hand.
*/
extern unsigned short eval_flushes[]; /* length:7169 elements:286 */

/*
 ** this is a table lookup for all non-flush hands consisting
 ** of three unique ranks (i.e.  either Straights or High Card
 ** hands).  it's similar to the above "flushes" array.
 */
extern unsigned short eval_unique3[]; /* length:7169 elements:286 */

#ifndef EVAL_USE_HASH

/*
 ** this is a table lookup for all other combinations
 ** (i.e. Pairs or Leopards)
 */
extern unsigned short eval_others[]; /* length:68922 elements:169 */

#else

/*
 ** these arrays were generated by hashgenerator
 ** this is a hash helper table
 */
extern unsigned short eval_hash_table[]; /* length:32 */

/*
 ** this is a hashed table lookup for all other combinations
 ** (i.e. Pairs or Leopards)
 */
extern unsigned short eval_hash_others[]; /* length:256 */
#endif

/*
** each of the thirteen card ranks has its own prime number
**
** deuce = 2
** trey  = 3
** four  = 5
** five  = 7
** ...
** king  = 37
** ace   = 41
*/
extern unsigned int eval_primes[];

#endif /* EVAL_ARRAYS_H_ */
